// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_GpqWaFzFOicVHzveHWir-8OL6hqpkBE',
    appId: '1:105869476795:web:c39ddf3fc874e974b6ba9e',
    messagingSenderId: '105869476795',
    projectId: 'expense-tracker-16daf',
    authDomain: 'expense-tracker-16daf.firebaseapp.com',
    storageBucket: 'expense-tracker-16daf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTsFwgwqs5aL_XzH3olrNtzJVeHXh_Lis',
    appId: '1:105869476795:android:3e500df847c3cad6b6ba9e',
    messagingSenderId: '105869476795',
    projectId: 'expense-tracker-16daf',
    storageBucket: 'expense-tracker-16daf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgxTY75O-wS0QW91WQf9h5yJ9wiMUBRB8',
    appId: '1:105869476795:ios:f6c9222c2d01bd6ab6ba9e',
    messagingSenderId: '105869476795',
    projectId: 'expense-tracker-16daf',
    storageBucket: 'expense-tracker-16daf.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
